
export enum AppSecretKeys {
  CLERK_SECRET_KEY = 'CLERK_SECRET_KEY',
  CLERK_PUBLISHABLE_KEY = 'CLERK_PUBLISHABLE_KEY',
  ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY',
  OPENAI_API_KEY = 'OPENAI_API_KEY',
}
