import { QuestTask, QuestQuestion, QuestEntity } from '../../../../../../src/services/quests/types';

export const workPersonalityTask: Omit<QuestTask, 'pk' | 'sk'> = {
  entity: QuestEntity.TASK,
  taskId: 'work_personality',
  title: 'Find Your Perfect Career Match',
  description: 'Discover your unique work personality type and unlock careers where you will naturally thrive. Find out if you are a Doer, Thinker, Creator, Helper, Persuader, or Organizer and explore paths aligned with your strengths.',
  illustration: 'compass',
  framework: "Holland's RIASEC Model",
  order: 1,
  scoringLogic: {
    scale: 'LIKERT_1_7',
    reverseQuestions: [],
    ranges: {
      realistic: [1, 7],
      investigative: [1, 7],
      artistic: [1, 7],
      social: [1, 7],
      enterprising: [1, 7],
      conventional: [1, 7],
    },
  },
  interpretations: [
    {
      category: 'realistic',
      range: [5.01, 7],
      label: 'The Doer',
      description: 'You are a builder, a maker, a creator of tangible things. Hands-on work with real results energizes you—you see a project through from start to finish.',
      traits: [
        'Thrives with hands-on work',
        'Loves tangible results',
        'Naturally mechanically inclined',
        'Builds and creates with skill',
      ],
      recommendations: [
        'Explore careers in engineering, construction, or skilled trades',
        'Seek roles with tangible outputs and measurable results',
        'Consider technical certifications to enhance skills',
        'Look for work environments with practical problem-solving',
      ],
    },
    {
      category: 'investigative',
      range: [5.01, 7],
      label: 'The Thinker',
      description: 'Your mind is your greatest tool. Complex problems excite you, research energizes you, and intellectual challenges feel like puzzles waiting to be solved.',
      traits: [
        'Sharp analytical mind',
        'Naturally curious researcher',
        'Loves complex puzzles',
        'Thrives on intellectual depth',
      ],
      recommendations: [
        'Consider careers in science, research, or data analysis',
        'Pursue advanced degrees or specialized training',
        'Seek roles with intellectual autonomy',
        'Engage in continuous learning and skill development',
      ],
    },
    {
      category: 'artistic',
      range: [5.01, 7],
      label: 'The Creator',
      description: 'You see the world differently. Creativity flows through everything you do—you express ideas in original ways and thrive where innovation is celebrated.',
      traits: [
        'Naturally creative and imaginative',
        'Expresses original ideas beautifully',
        'Thrives in open, unstructured spaces',
        'Sees beauty and possibility everywhere',
      ],
      recommendations: [
        'Explore careers in design, arts, writing, or entertainment',
        'Seek roles that reward innovation and creativity',
        'Build a portfolio showcasing your creative work',
        'Network within creative communities and industries',
      ],
    },
    {
      category: 'social',
      range: [5.01, 7],
      label: 'The Helper',
      description: 'People are your passion. You light up when helping others grow, teaching what you know, and making genuine human connections that create positive change.',
      traits: [
        'Deeply empathetic and caring',
        'Natural teacher and mentor',
        'Creates meaningful connections',
        'Driven by making a difference',
      ],
      recommendations: [
        'Consider careers in education, healthcare, or counseling',
        'Seek roles with strong interpersonal components',
        'Develop skills in communication and emotional intelligence',
        'Look for organizations with strong social missions',
      ],
    },
    {
      category: 'enterprising',
      range: [5.01, 7],
      label: 'The Persuader',
      description: 'You are a natural leader who inspires action. Competition energizes you, goals drive you, and you have the influence to move people toward a vision.',
      traits: [
        'Natural-born leader',
        'Compellingly persuasive',
        'Thrives in competition',
        'Achieves ambitious goals',
      ],
      recommendations: [
        'Explore careers in business, sales, or entrepreneurship',
        'Seek leadership roles or management tracks',
        'Develop skills in negotiation and strategic thinking',
        'Network actively and build professional relationships',
      ],
    },
    {
      category: 'conventional',
      range: [5.01, 7],
      label: 'The Organizer',
      description: 'Order is your superpower. You bring structure to chaos, attention to detail that others miss, and reliability that teams depend on.',
      traits: [
        'Master of organization',
        'Creates systems that work',
        'Incredibly reliable and thorough',
        'Brings order to complexity',
      ],
      recommendations: [
        'Consider careers in accounting, administration, or operations',
        'Seek roles with defined processes and quality standards',
        'Develop expertise in systems and organizational tools',
        'Look for stable organizations with established procedures',
      ],
    },
  ],
};

export const workPersonalityQuestions: Omit<QuestQuestion, 'pk' | 'sk'>[] = [
  {
    entity: QuestEntity.QUESTION,
    taskId: 'work_personality',
    questionId: 'wp_q1',
    text: 'I enjoy working with my hands and building tangible things.',
    scale: 'LIKERT_1_7',
    isReverse: false,
    domain: 'realistic',
    order: 1,
  },
  {
    entity: QuestEntity.QUESTION,
    taskId: 'work_personality',
    questionId: 'wp_q2',
    text: 'I prefer analyzing data and solving complex problems.',
    scale: 'LIKERT_1_7',
    isReverse: false,
    domain: 'investigative',
    order: 2,
  },
  {
    entity: QuestEntity.QUESTION,
    taskId: 'work_personality',
    questionId: 'wp_q3',
    text: 'I am energized by creative expression and original ideas.',
    scale: 'LIKERT_1_7',
    isReverse: false,
    domain: 'artistic',
    order: 3,
  },
  {
    entity: QuestEntity.QUESTION,
    taskId: 'work_personality',
    questionId: 'wp_q4',
    text: 'I find fulfillment in helping and mentoring others.',
    scale: 'LIKERT_1_7',
    isReverse: false,
    domain: 'social',
    order: 4,
  },
  {
    entity: QuestEntity.QUESTION,
    taskId: 'work_personality',
    questionId: 'wp_q5',
    text: 'I enjoy leading projects and persuading others.',
    scale: 'LIKERT_1_7',
    isReverse: false,
    domain: 'enterprising',
    order: 5,
  },
];
