import { QuestTask, QuestQuestion, QuestEntity } from '../../../../../../src/services/quests/types';

export const attachmentStyleTask: Omit<QuestTask, 'pk' | 'sk'> = {
  entity: QuestEntity.TASK,
  taskId: 'attachment_style',
  title: 'Decode Your Attachment Style',
  description: 'Uncover how you connect in relationships and discover if you have anxious, avoidant, or secure attachment patterns. Learn how your early experiences shape your love life and how to build healthier connections.',
  illustration: 'heart',
  framework: 'Experiences in Close Relationships - Revised (ECR-R)',
  order: 1,
  scoringLogic: {
    scale: 'LIKERT_1_7',
    reverseQuestions: ['as_q2', 'as_q5'],
    ranges: {
      anxiety_low: [1, 3.5],
      anxiety_moderate: [3.51, 5.5],
      anxiety_high: [5.51, 7],
      avoidance_low: [1, 3.5],
      avoidance_moderate: [3.51, 5.5],
      avoidance_high: [5.51, 7],
    },
  },
  interpretations: [
    {
      category: 'anxiety_low',
      range: [1, 3.5],
      label: 'Secure Heart',
      description: 'You approach relationships from a place of security. You trust that you are valued and loved, freeing you to connect deeply without constant worry.',
      traits: [
        'Secure sense of worth',
        'Trusts relationships naturally',
        'Comfortable with intimacy',
        'At peace with connection',
      ],
      recommendations: [
        'Maintain healthy relationship practices',
        'Continue nurturing secure attachments',
        'Support partners who may have higher anxiety',
        'Model secure attachment for others',
      ],
    },
    {
      category: 'anxiety_moderate',
      range: [3.51, 5.5],
      label: 'Growing Security',
      description: 'You are building a more secure foundation in relationships. While occasional worries arise, you are developing the inner trust that creates lasting connections.',
      traits: [
        'Building relationship confidence',
        'Learning to self-soothe',
        'Growing trust in connections',
        'Developing secure patterns',
      ],
      recommendations: [
        'Practice self-soothing when insecurity arises',
        'Communicate needs clearly rather than seeking indirect validation',
        'Work on building self-esteem independent of relationships',
        'Consider attachment-focused therapy if concerns persist',
      ],
    },
    {
      category: 'anxiety_high',
      range: [5.51, 7],
      label: 'Healing Your Heart',
      description: 'Your heart cares deeply—sometimes too much. Understanding these patterns is your first step toward the security and peace you deserve in relationships.',
      traits: [
        'Deeply caring heart',
        'Ready to build inner security',
        'Learning to trust the process',
        'Transforming anxiety into strength',
      ],
      recommendations: [
        'Work with a therapist specializing in attachment issues',
        'Practice mindfulness to manage anxiety when triggered',
        'Explore childhood experiences that shaped attachment patterns',
        'Build self-worth through personal accomplishments and self-care',
      ],
    },
    {
      category: 'avoidance_low',
      range: [1, 3.5],
      label: 'Open-Hearted',
      description: 'You embrace emotional closeness naturally. Trusting others comes easily, and you experience the full richness of intimate connection.',
      traits: [
        'Naturally embraces intimacy',
        'Trusts and depends on others easily',
        'Openly shares feelings',
        'Treasures close bonds',
      ],
      recommendations: [
        'Continue fostering deep emotional connections',
        'Support partners who may have avoidant tendencies',
        'Maintain healthy boundaries while staying connected',
        'Model emotional openness in relationships',
      ],
    },
    {
      category: 'avoidance_moderate',
      range: [3.51, 5.5],
      label: 'Opening Up',
      description: 'You are learning to let people in. While vulnerability still feels uncomfortable sometimes, you are building the trust muscles that create deep connection.',
      traits: [
        'Learning to be vulnerable',
        'Growing comfort with closeness',
        'Balancing independence and intimacy',
        'Building trust gradually',
      ],
      recommendations: [
        'Practice gradually increasing emotional vulnerability',
        'Reflect on fears that prevent deeper connection',
        'Communicate your comfort levels with partners',
        'Challenge beliefs that intimacy equals loss of independence',
      ],
    },
    {
      category: 'avoidance_high',
      range: [5.51, 7],
      label: 'Discovering Connection',
      description: 'Independence has served you well—but deeper connection awaits. Understanding these patterns opens the door to intimacy that feels safe and fulfilling.',
      traits: [
        'Strong sense of independence',
        'Learning to trust gradually',
        'Discovering safe vulnerability',
        'Opening to deeper connection',
      ],
      recommendations: [
        'Explore attachment patterns with a therapist',
        'Practice small acts of vulnerability in safe relationships',
        'Understand how avoidance protects you but limits connection',
        'Work on building trust gradually in relationships',
      ],
    },
  ],
};

export const attachmentStyleQuestions: Omit<QuestQuestion, 'pk' | 'sk'>[] = [
  {
    entity: QuestEntity.QUESTION,
    taskId: 'attachment_style',
    questionId: 'as_q1',
    text: 'I worry that people won\'t care about me as much as I care about them.',
    scale: 'LIKERT_1_7',
    isReverse: false,
    domain: 'anxiety',
    order: 1,
  },
  {
    entity: QuestEntity.QUESTION,
    taskId: 'attachment_style',
    questionId: 'as_q2',
    text: 'I am comfortable being emotionally close to others.',
    scale: 'LIKERT_1_7',
    isReverse: true,
    domain: 'avoidance',
    order: 2,
  },
  {
    entity: QuestEntity.QUESTION,
    taskId: 'attachment_style',
    questionId: 'as_q3',
    text: 'I need a lot of reassurance that people care about me.',
    scale: 'LIKERT_1_7',
    isReverse: false,
    domain: 'anxiety',
    order: 3,
  },
  {
    entity: QuestEntity.QUESTION,
    taskId: 'attachment_style',
    questionId: 'as_q4',
    text: 'I prefer not to show others how I feel deep down.',
    scale: 'LIKERT_1_7',
    isReverse: false,
    domain: 'avoidance',
    order: 4,
  },
  {
    entity: QuestEntity.QUESTION,
    taskId: 'attachment_style',
    questionId: 'as_q5',
    text: 'I find it easy to trust and depend on others.',
    scale: 'LIKERT_1_7',
    isReverse: true,
    domain: 'avoidance',
    order: 5,
  },
];
